// Code generated by internal/gen; DO NOT EDIT.

// Package series holds the frozen ephemeris coefficient tables (VSOP87D,
// ELP2000-82B and the IAU 2000 nutation series) that the astronomy package
// evaluates, regenerated from testdata/ephemeris by internal/gen. The maps
// here let the coefficient-identity test walk every emitted series without a
// hand-maintained list.
//
//go:generate go run ../../cmd/gen
package series

// Float64Series maps the Go name of every float64 table to the table.
var Float64Series = map[string][]float64{
	"EAR_B":                        EAR_B,
	"EAR_B_PRECISE":                EAR_B_PRECISE,
	"EAR_L":                        EAR_L,
	"EAR_L_PRECISE":                EAR_L_PRECISE,
	"EAR_R":                        EAR_R,
	"EAR_R_COARSE":                 EAR_R_COARSE,
	"JUP_B":                        JUP_B,
	"JUP_L":                        JUP_L,
	"JUP_R":                        JUP_R,
	"MAR_B":                        MAR_B,
	"MAR_L":                        MAR_L,
	"MAR_R":                        MAR_R,
	"MER_B":                        MER_B,
	"MER_L":                        MER_L,
	"MER_R":                        MER_R,
	"MOON_DISTANCE_COARSE_LINEAR":  MOON_DISTANCE_COARSE_LINEAR,
	"MOON_DISTANCE_COARSE_QUARTIC": MOON_DISTANCE_COARSE_QUARTIC,
	"MOON_DISTANCE_LINEAR":         MOON_DISTANCE_LINEAR,
	"MOON_DISTANCE_QUARTIC":        MOON_DISTANCE_QUARTIC,
	"MOON_DISTANCE_TRACK_LINEAR":   MOON_DISTANCE_TRACK_LINEAR,
	"MOON_DISTANCE_TRACK_QUARTIC":  MOON_DISTANCE_TRACK_QUARTIC,
	"MOON_LATITUDE_COARSE_LINEAR":  MOON_LATITUDE_COARSE_LINEAR,
	"MOON_LATITUDE_COARSE_QUARTIC": MOON_LATITUDE_COARSE_QUARTIC,
	"MOON_LATITUDE_LINEAR":         MOON_LATITUDE_LINEAR,
	"MOON_LATITUDE_QUARTIC":        MOON_LATITUDE_QUARTIC,
	"MOON_LONGITUDE_LINEAR":        MOON_LONGITUDE_LINEAR,
	"MOON_LONGITUDE_QUARTIC":       MOON_LONGITUDE_QUARTIC,
	"MOON_MEAN_LONGITUDE":          MOON_MEAN_LONGITUDE,
	"NUTATION_EPS":                 NUTATION_EPS,
	"NUTATION_PSI":                 NUTATION_PSI,
	"SAT_B":                        SAT_B,
	"SAT_L":                        SAT_L,
	"SAT_R":                        SAT_R,
	"VEN_B":                        VEN_B,
	"VEN_L":                        VEN_L,
	"VEN_R":                        VEN_R,
}

// Int8Series maps the Go name of every int8 table to the table.
var Int8Series = map[string][]int8{
	"NUTATION_EPS_ARGS": NUTATION_EPS_ARGS,
	"NUTATION_PSI_ARGS": NUTATION_PSI_ARGS,
}

// Scalars maps the Go name of every emitted scalar constant to its value.
var Scalars = map[string]float64{
	"NUTATION_MAX_MULTIPLIER": NUTATION_MAX_MULTIPLIER,
}
